apiVersion: v1
kind: Service
metadata:
  labels:
    app: melospiza-web
  name: melospiza-web
spec:
  ports:
   - port: 80
     protocol: TCP
     targetPort: 80
     nodePort: 30333
  selector:
    app: melospiza-web
  type: NodePort
