apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: synergy-web
  name: synergy-web-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: synergy-web
  strategy: {}
  template:
    metadata:
      labels:
        app: synergy-web
    spec:
      containers:
       - image: ghcr.io/lokeshb003/synergy_docker_image:master
         name: synergy-web
         imagePullPolicy: Always
         ports:
          - containerPort: 3000
