apiVersion: v1
kind: Service
metadata:
  labels:
    app: synergy-web
  name: synergy-web-service
spec:
  ports:
   - port: 80
     protocol: TCP
     targetPort: 80
     nodePort: 30334
  selector:
    app: synergy-web
  type: LoadBalancer
