apiVersion: v1
kind: Service
metadata:
  labels:
    app: synergy-web
  name: synergy-web-service
spec:
  ports:
   - port: 3000
     protocol: TCP
     targetPort: 3000
     nodePort: 30222
  selector:
    app: synergy-web
  type: LoadBalancer
